<template>
  <div class="loader">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
      <path d="M33 50A17 17 0 0 0 67 50A17 18.3 0 0 1 33 50" fill="#8457ed" stroke="none">
        <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50.65;360 50 50.65"></animateTransform>
      </path>
      <!-- [ldio] generated by https://loading.io/ --></svg>
  </div>
</template>

<style>
.loader {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(255, 255, 255, .8);
  z-index: 1;

  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
